#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from HW4-sql.ypp  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDENT	258
#define	NUMBER	259
#define	STRING	260
#define	NUL	261
#define	SELECT	262
#define	AS	263
#define	FROM	264
#define	WHERE	265
#define	GROUP	266
#define	BY	267
#define	HAVING	268
#define	ORDER	269
#define	ASC	270
#define	DESC	271
#define	INSERT	272
#define	INTO	273
#define	VALUES	274
#define	UPDATE	275
#define	SET	276
#define	DELETE	277
#define	CREATE	278
#define	TABLE	279
#define	DESCRIBE	280
#define	SHOW	281
#define	TABLES	282
#define	DROP	283
#define	PRIMARY	284
#define	DISTINCT	285
#define	KEY	286
#define	COUNT	287
#define	AVG	288
#define	NOTEQ	289
#define	GEQ	290
#define	LEQ	291
#define	AND	292
#define	OR	293
#define	NOT	294
#define	IN	295
#define	QUIT	296


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDENT;
static const int NUMBER;
static const int STRING;
static const int NUL;
static const int SELECT;
static const int AS;
static const int FROM;
static const int WHERE;
static const int GROUP;
static const int BY;
static const int HAVING;
static const int ORDER;
static const int ASC;
static const int DESC;
static const int INSERT;
static const int INTO;
static const int VALUES;
static const int UPDATE;
static const int SET;
static const int DELETE;
static const int CREATE;
static const int TABLE;
static const int DESCRIBE;
static const int SHOW;
static const int TABLES;
static const int DROP;
static const int PRIMARY;
static const int DISTINCT;
static const int KEY;
static const int COUNT;
static const int AVG;
static const int NOTEQ;
static const int GEQ;
static const int LEQ;
static const int AND;
static const int OR;
static const int NOT;
static const int IN;
static const int QUIT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDENT=258
	,NUMBER=259
	,STRING=260
	,NUL=261
	,SELECT=262
	,AS=263
	,FROM=264
	,WHERE=265
	,GROUP=266
	,BY=267
	,HAVING=268
	,ORDER=269
	,ASC=270
	,DESC=271
	,INSERT=272
	,INTO=273
	,VALUES=274
	,UPDATE=275
	,SET=276
	,DELETE=277
	,CREATE=278
	,TABLE=279
	,DESCRIBE=280
	,SHOW=281
	,TABLES=282
	,DROP=283
	,PRIMARY=284
	,DISTINCT=285
	,KEY=286
	,COUNT=287
	,AVG=288
	,NOTEQ=289
	,GEQ=290
	,LEQ=291
	,AND=292
	,OR=293
	,NOT=294
	,IN=295
	,QUIT=296


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IDENT=258;
const int YY_parse_CLASS::NUMBER=259;
const int YY_parse_CLASS::STRING=260;
const int YY_parse_CLASS::NUL=261;
const int YY_parse_CLASS::SELECT=262;
const int YY_parse_CLASS::AS=263;
const int YY_parse_CLASS::FROM=264;
const int YY_parse_CLASS::WHERE=265;
const int YY_parse_CLASS::GROUP=266;
const int YY_parse_CLASS::BY=267;
const int YY_parse_CLASS::HAVING=268;
const int YY_parse_CLASS::ORDER=269;
const int YY_parse_CLASS::ASC=270;
const int YY_parse_CLASS::DESC=271;
const int YY_parse_CLASS::INSERT=272;
const int YY_parse_CLASS::INTO=273;
const int YY_parse_CLASS::VALUES=274;
const int YY_parse_CLASS::UPDATE=275;
const int YY_parse_CLASS::SET=276;
const int YY_parse_CLASS::DELETE=277;
const int YY_parse_CLASS::CREATE=278;
const int YY_parse_CLASS::TABLE=279;
const int YY_parse_CLASS::DESCRIBE=280;
const int YY_parse_CLASS::SHOW=281;
const int YY_parse_CLASS::TABLES=282;
const int YY_parse_CLASS::DROP=283;
const int YY_parse_CLASS::PRIMARY=284;
const int YY_parse_CLASS::DISTINCT=285;
const int YY_parse_CLASS::KEY=286;
const int YY_parse_CLASS::COUNT=287;
const int YY_parse_CLASS::AVG=288;
const int YY_parse_CLASS::NOTEQ=289;
const int YY_parse_CLASS::GEQ=290;
const int YY_parse_CLASS::LEQ=291;
const int YY_parse_CLASS::AND=292;
const int YY_parse_CLASS::OR=293;
const int YY_parse_CLASS::NOT=294;
const int YY_parse_CLASS::IN=295;
const int YY_parse_CLASS::QUIT=296;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		163
#define	YYFLAG		-32768
#define	YYNTBASE	53

#define YYTRANSLATE(x) ((unsigned)(x) <= 296 ? yytranslate[x] : 78)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    43,
    44,    51,    49,    46,    50,     2,    52,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    42,    48,
    45,    47,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     8,    17,    23,    26,    36,    43,    51,
    55,    59,    64,    67,    69,    71,    73,    77,    83,    89,
    95,    99,   103,   105,   110,   114,   116,   120,   122,   124,
   126,   135,   136,   139,   140,   143,   144,   148,   150,   154,
   156,   157,   161,   163,   167,   169,   172,   175,   177,   180,
   183,   185,   186,   189,   193,   197,   199,   201,   206,   211,
   213,   217,   219,   221,   223,   227,   231,   235,   237,   241,
   243,   246,   250,   252,   254,   256,   258,   260,   262,   264,
   266,   268,   270,   272,   274
};

static const short yyrhs[] = {    -1,
    53,    54,     0,    53,    41,    42,     0,    17,    18,    55,
    19,    43,    74,    44,    42,     0,    17,    18,    55,    61,
    42,     0,    61,    42,     0,    20,    55,    21,    56,    45,
    57,    10,    57,    42,     0,    22,     9,    55,    10,    57,
    42,     0,    23,    24,    55,    43,    75,    44,    42,     0,
    25,    55,    42,     0,    26,    27,    42,     0,    28,    24,
    55,    42,     0,     1,    42,     0,     3,     0,     3,     0,
    60,     0,    57,    77,    60,     0,    57,    77,    43,    57,
    44,     0,    57,    77,    43,    61,    44,     0,    57,    77,
    43,    74,    44,     0,    43,    61,    44,     0,    43,    57,
    44,     0,    58,     0,     3,    43,    59,    44,     0,     3,
    43,    44,     0,    57,     0,    59,    46,    57,     0,     3,
     0,     4,     0,     5,     0,     7,    70,     9,    73,    62,
    64,    63,    67,     0,     0,    10,    57,     0,     0,    13,
    57,     0,     0,    11,    12,    65,     0,    66,     0,    65,
    46,    66,     0,    56,     0,     0,    14,    12,    68,     0,
    69,     0,    68,    46,    69,     0,     4,     0,     4,    15,
     0,     4,    16,     0,    56,     0,    56,    15,     0,    56,
    16,     0,    71,     0,     0,    30,    71,     0,    70,    46,
    71,     0,    57,     8,    56,     0,    56,     0,    72,     0,
    32,    43,    56,    44,     0,    33,    43,    56,    44,     0,
    55,     0,    73,    46,    55,     0,     4,     0,     5,     0,
     6,     0,    74,    46,     4,     0,    74,    46,     5,     0,
    74,    46,     6,     0,    76,     0,    75,    46,    76,     0,
    56,     0,    56,    31,     0,    56,    29,    31,     0,    45,
     0,    34,     0,    47,     0,    48,     0,    35,     0,    36,
     0,    49,     0,    50,     0,    51,     0,    52,     0,    37,
     0,    38,     0,    40,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    45,    46,    47,    50,    53,    56,    59,    62,    65,    68,
    72,    76,    79,    84,    90,    96,    97,    98,    99,   100,
   101,   102,   103,   107,   109,   113,   115,   120,   122,   124,
   128,   138,   139,   142,   143,   146,   147,   151,   153,   157,
   160,   161,   165,   167,   171,   173,   175,   177,   179,   181,
   185,   187,   187,   188,   192,   194,   196,   200,   201,   204,
   206,   210,   211,   212,   213,   214,   215,   221,   223,   227,
   229,   231,   235,   236,   237,   238,   239,   240,   241,   242,
   243,   244,   245,   246,   247
};

static const char * const yytname[] = {   "$","error","$illegal.","IDENT","NUMBER",
"STRING","NUL","SELECT","AS","FROM","WHERE","GROUP","BY","HAVING","ORDER","ASC",
"DESC","INSERT","INTO","VALUES","UPDATE","SET","DELETE","CREATE","TABLE","DESCRIBE",
"SHOW","TABLES","DROP","PRIMARY","DISTINCT","KEY","COUNT","AVG","NOTEQ","GEQ",
"LEQ","AND","OR","NOT","IN","QUIT","';'","'('","')'","'='","','","'>'","'<'",
"'+'","'-'","'*'","'/'","program","sql_command","tablename","colname","expr",
"fcall","fncargs","value","select_expr","whereclause","havingclause","groupclause",
"grouplist","groupspec","orderclause","orderlist","orderspec","projection","outcol",
"agr_func","join","data_list","column_decls","column_decl","bin_op",""
};
#endif

static const short yyr1[] = {     0,
    53,    53,    53,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    55,    56,    57,    57,    57,    57,    57,
    57,    57,    57,    58,    58,    59,    59,    60,    60,    60,
    61,    62,    62,    63,    63,    64,    64,    65,    65,    66,
    67,    67,    68,    68,    69,    69,    69,    69,    69,    69,
    70,    70,    70,    70,    71,    71,    71,    72,    72,    73,
    73,    74,    74,    74,    74,    74,    74,    75,    75,    76,
    76,    76,    77,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    77,    77,    77
};

static const short yyr2[] = {     0,
     0,     2,     3,     8,     5,     2,     9,     6,     7,     3,
     3,     4,     2,     1,     1,     1,     3,     5,     5,     5,
     3,     3,     1,     4,     3,     1,     3,     1,     1,     1,
     8,     0,     2,     0,     2,     0,     3,     1,     3,     1,
     0,     3,     1,     3,     1,     2,     2,     1,     2,     2,
     1,     0,     2,     3,     3,     1,     1,     4,     4,     1,
     3,     1,     1,     1,     3,     3,     3,     1,     3,     1,
     2,     3,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1
};

static const short yydefact[] = {     1,
     0,     0,    52,     0,     0,     0,     0,     0,     0,     0,
     0,     2,     0,    13,    28,    29,    30,     0,     0,     0,
     0,    56,     0,    23,    16,     0,    51,    57,     0,    14,
     0,     0,     0,     0,     0,     0,     3,     6,     0,    53,
     0,     0,    28,     0,     0,     0,    74,    77,    78,    83,
    84,    85,    73,    75,    76,    79,    80,    81,    82,     0,
     0,     0,     0,     0,     0,     0,    10,    11,     0,    25,
    26,     0,    15,     0,     0,    22,    21,    55,    28,     0,
    17,    60,    32,    54,     0,     0,     0,     0,     0,    12,
    24,     0,    58,    59,    29,    30,    64,     0,     0,     0,
     0,     0,    36,     0,     5,     0,     0,    70,     0,    68,
    27,    18,    19,    20,     0,    33,    61,     0,    34,    62,
    63,     0,     0,     8,     0,    71,     0,     0,    65,    66,
    67,     0,     0,    41,     0,     0,    72,     9,    69,    40,
    37,    38,    35,     0,    31,     4,     0,     0,     0,     7,
    39,    45,    48,    42,    43,    46,    47,    49,    50,     0,
    44,     0,     0
};

static const short yydefgoto[] = {     1,
    12,    31,    22,    23,    24,    72,    25,    13,   103,   134,
   119,   141,   142,   145,   154,   155,    26,    27,    28,    83,
   100,   109,   110,    60
};

static const short yypact[] = {-32768,
   129,   -33,    60,     4,    27,    22,    32,    27,    48,    52,
    42,-32768,    43,-32768,    51,-32768,-32768,    63,    46,    66,
    97,-32768,     2,-32768,-32768,    36,-32768,-32768,    27,-32768,
    78,    27,    27,    80,    92,    27,-32768,-32768,    15,-32768,
   117,   117,    95,   124,   103,   117,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,     3,
    27,    63,     5,   117,   138,   107,-32768,-32768,   111,-32768,
   200,    -3,-32768,   112,   119,-32768,-32768,-32768,-32768,    74,
-32768,-32768,    59,-32768,   122,   125,   121,    30,   117,-32768,
-32768,    30,-32768,-32768,   136,   139,-32768,   143,   140,    91,
    30,    27,   175,     9,-32768,    30,   162,   110,    98,-32768,
   200,-32768,-32768,-32768,   127,   200,-32768,   177,   188,-32768,
-32768,    99,    76,-32768,   172,-32768,   163,   117,-32768,-32768,
-32768,   117,    30,   192,   166,    30,-32768,-32768,-32768,-32768,
   174,-32768,   200,   210,-32768,-32768,   181,   117,    13,-32768,
-32768,    11,    56,   178,-32768,-32768,-32768,-32768,-32768,    13,
-32768,   225,-32768
};

static const short yypgoto[] = {-32768,
-32768,    -4,   -41,   -18,-32768,-32768,   167,   -19,-32768,-32768,
-32768,-32768,    93,-32768,-32768,    79,-32768,    -7,-32768,-32768,
   142,-32768,   114,-32768
};


#define	YYLAST		252


static const short yytable[] = {    74,
    75,    45,    44,    34,    78,    79,    16,    17,    14,    46,
    40,     3,   120,   121,    97,    73,   152,    43,    16,    17,
    71,    29,    87,    85,    63,   156,   157,    65,    66,    30,
    32,    69,    43,    16,    17,    47,    48,    49,    50,    51,
    91,    52,    92,    86,    61,    80,    53,   108,    54,    55,
    56,    57,    58,    59,    84,    33,    82,    21,    70,   -15,
    99,    98,    15,    16,    17,    15,    16,    17,   101,   107,
   158,   159,    21,   111,    35,    36,    43,    95,    96,    97,
     3,    62,   116,    37,    38,   136,   108,   123,    41,    18,
   140,    19,    20,    39,    19,    20,   -15,   117,    64,    43,
    16,    17,    21,     3,   102,    21,   140,   153,    42,    47,
    48,    49,    50,    51,   143,    52,    21,   147,   153,    73,
    53,    67,    54,    55,    56,    57,    58,    59,   162,     2,
   129,   130,   131,    68,   114,     3,   115,    39,   125,    21,
   126,   127,   135,   128,   115,     4,    77,    88,     5,    89,
     6,     7,    90,     8,     9,    93,    10,    47,    48,    49,
    50,    51,    94,    52,   104,   106,   105,    76,    53,    11,
    54,    55,    56,    57,    58,    59,    47,    48,    49,    50,
    51,   -62,    52,   113,   -63,   118,   112,    53,   132,    54,
    55,    56,    57,    58,    59,    47,    48,    49,    50,    51,
   133,    52,   137,   124,   138,   144,    53,   146,    54,    55,
    56,    57,    58,    59,    47,    48,    49,    50,    51,   148,
    52,   149,   150,   160,   163,    53,    81,    54,    55,    56,
    57,    58,    59,    47,    48,    49,    50,    51,   161,    52,
   151,   139,     0,     0,    53,   122,    54,    55,    56,    57,
    58,    59
};

static const short yycheck[] = {    41,
    42,    21,    21,     8,    46,     3,     4,     5,    42,     8,
    18,     7,     4,     5,     6,     3,     4,     3,     4,     5,
    39,    18,    64,    19,    29,    15,    16,    32,    33,     3,
     9,    36,     3,     4,     5,    34,    35,    36,    37,    38,
    44,    40,    46,    63,     9,    43,    45,    89,    47,    48,
    49,    50,    51,    52,    62,    24,    61,    43,    44,     9,
    80,    80,     3,     4,     5,     3,     4,     5,    10,    88,
    15,    16,    43,    92,    27,    24,     3,     4,     5,     6,
     7,    46,   101,    42,    42,    10,   128,   106,    43,    30,
   132,    32,    33,    43,    32,    33,    46,   102,    21,     3,
     4,     5,    43,     7,    46,    43,   148,   149,    43,    34,
    35,    36,    37,    38,   133,    40,    43,   136,   160,     3,
    45,    42,    47,    48,    49,    50,    51,    52,     0,     1,
     4,     5,     6,    42,    44,     7,    46,    43,    29,    43,
    31,    44,    44,    46,    46,    17,    44,    10,    20,    43,
    22,    23,    42,    25,    26,    44,    28,    34,    35,    36,
    37,    38,    44,    40,    43,    45,    42,    44,    45,    41,
    47,    48,    49,    50,    51,    52,    34,    35,    36,    37,
    38,    46,    40,    44,    46,    11,    44,    45,    12,    47,
    48,    49,    50,    51,    52,    34,    35,    36,    37,    38,
    13,    40,    31,    42,    42,    14,    45,    42,    47,    48,
    49,    50,    51,    52,    34,    35,    36,    37,    38,    46,
    40,    12,    42,    46,     0,    45,    60,    47,    48,    49,
    50,    51,    52,    34,    35,    36,    37,    38,   160,    40,
   148,   128,    -1,    -1,    45,   104,    47,    48,    49,    50,
    51,    52
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 3:
#line 47 "HW4-sql.ypp"
{ YYACCEPT; ;
    break;}
case 4:
#line 51 "HW4-sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(makeexpr(OP_INSERTROW, 2, yyvsp[-5], yyvsp[-2]))))); yyval=0; freen=0; ;
    break;}
case 5:
#line 54 "HW4-sql.ypp"
{ printf("Multi-row insert not implemented yet\n"); freen=0; ;
    break;}
case 6:
#line 57 "HW4-sql.ypp"
{ print_relation(evalexpr(optimize(compile(cvt_itoe(yyvsp[-1]))))); freen=0; ;
    break;}
case 7:
#line 60 "HW4-sql.ypp"
{  evalexpr(optimize(compile(cvt_itoe( update_table( yyvsp[-7], makeexpr(OP_SET, 2, yyvsp[-5], yyvsp[-3]), yyvsp[-1]  ) )))); ;
    break;}
case 8:
#line 63 "HW4-sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(makeexpr(OP_DELETE, 2, yyvsp[-3], yyvsp[-1]))))); ;
    break;}
case 9:
#line 66 "HW4-sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(makeexpr(OP_CREATETABLE, 2, yyvsp[-4], yyvsp[-2]))))); yyval=0; freen=0; ;
    break;}
case 10:
#line 69 "HW4-sql.ypp"
{ printf("DESCRIBE not implemented yet\n"); freen=0; ;
    break;}
case 11:
#line 73 "HW4-sql.ypp"
{ printf("SHOW TABLES not implemented yet\n"); freen=0; ;
    break;}
case 12:
#line 77 "HW4-sql.ypp"
{ evalexpr(optimize(compile(cvt_itoe(drop_table(cvt_itoe(yyvsp[-1])))))); ;
    break;}
case 13:
#line 80 "HW4-sql.ypp"
{ freen = 0; ;
    break;}
case 14:
#line 85 "HW4-sql.ypp"
{
		  yyval = setname(OP_TABLENAME, yyvsp[0]);
		;
    break;}
case 15:
#line 91 "HW4-sql.ypp"
{
		  yyval = setname(OP_COLNAME, yyvsp[0]);
		;
    break;}
case 17:
#line 97 "HW4-sql.ypp"
{ yyval = makeexpr(yyvsp[-1], 2, yyvsp[-2], yyvsp[0]); ;
    break;}
case 18:
#line 98 "HW4-sql.ypp"
{ yyval = makeexpr(yyvsp[-3], 2, yyvsp[-4], yyvsp[-1]); ;
    break;}
case 19:
#line 99 "HW4-sql.ypp"
{ yyval = makeexpr(yyvsp[-3], 2, yyvsp[-4], yyvsp[-1]); ;
    break;}
case 20:
#line 100 "HW4-sql.ypp"
{ yyval = makeexpr(yyvsp[-3], 2, yyvsp[-4], yyvsp[-1]); ;
    break;}
case 21:
#line 101 "HW4-sql.ypp"
{ yyval = yyvsp[-1]; ;
    break;}
case 22:
#line 102 "HW4-sql.ypp"
{ yyval = yyvsp[-1]; ;
    break;}
case 23:
#line 103 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 24:
#line 108 "HW4-sql.ypp"
{ yyval = makeexpr(OP_FCALL, 2, setname(OP_FNAME, yyvsp[-3]), yyvsp[-1]); ;
    break;}
case 25:
#line 110 "HW4-sql.ypp"
{ yyval = makeexpr(OP_FCALL, 2, setname(OP_FNAME, yyvsp[-2]), 0); ;
    break;}
case 26:
#line 114 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 27:
#line 116 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 28:
#line 121 "HW4-sql.ypp"
{ yyval = setname(OP_COLNAME, yyvsp[0]); ;
    break;}
case 29:
#line 123 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 30:
#line 125 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 31:
#line 129 "HW4-sql.ypp"
{ yyval = yyvsp[-4];
		  if(yyvsp[-3]) yyval = makeexpr(OP_SELECTION, 2, yyval, yyvsp[-3]);
		  if(yyvsp[-2]) yyval = makeexpr(OP_GROUP, 2, yyval, yyvsp[-2]);
		  yyval = makeexpr(OP_PROJECTION, 2, yyval, yyvsp[-6]);
		  if(yyvsp[-1]) yyval = makeexpr(OP_SELECTION, 2, yyval, yyvsp[-1]);
		  if(yyvsp[0]) yyval = makeexpr(OP_SORT, 2, yyval, yyvsp[0]);
		;
    break;}
case 32:
#line 138 "HW4-sql.ypp"
{ yyval = 0; ;
    break;}
case 33:
#line 139 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 34:
#line 142 "HW4-sql.ypp"
{ yyval = 0; ;
    break;}
case 35:
#line 143 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 36:
#line 146 "HW4-sql.ypp"
{ yyval = 0; ;
    break;}
case 37:
#line 148 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 38:
#line 152 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 39:
#line 154 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 41:
#line 160 "HW4-sql.ypp"
{ yyval = 0; ;
    break;}
case 42:
#line 162 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 43:
#line 166 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 44:
#line 168 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 45:
#line 172 "HW4-sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, yyvsp[0], 0); ;
    break;}
case 46:
#line 174 "HW4-sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, yyvsp[-1], 0); ;
    break;}
case 47:
#line 176 "HW4-sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, yyvsp[-1], makeexpr(OP_NULL, 0, 0, 0)); ;
    break;}
case 48:
#line 178 "HW4-sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, setname(OP_COLNAME, yyvsp[0]), 0); ;
    break;}
case 49:
#line 180 "HW4-sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, setname(OP_COLNAME, yyvsp[-1]), 0); ;
    break;}
case 50:
#line 182 "HW4-sql.ypp"
{ yyval = makeexpr(OP_SORTSPEC, 2, setname(OP_COLNAME, yyvsp[-1]), makeexpr(OP_NULL, 0, 0, 0)); ;
    break;}
case 51:
#line 186 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 53:
#line 187 "HW4-sql.ypp"
{ yyval = makeexpr(OP_DISTINCT, 1, makeexpr(OP_RLIST, 2, yyvsp[0], 0), 0); ;
    break;}
case 54:
#line 189 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 55:
#line 193 "HW4-sql.ypp"
{ yyval = makeexpr(OP_OUTCOLNAME, 2, yyvsp[-2], yyvsp[0]); ;
    break;}
case 56:
#line 195 "HW4-sql.ypp"
{ yyval = makeexpr(OP_OUTCOLNAME, 2, yyvsp[0], yyvsp[0]); ;
    break;}
case 57:
#line 197 "HW4-sql.ypp"
{ yyval = yyvsp[0] ;
    break;}
case 58:
#line 200 "HW4-sql.ypp"
{ yyval =  makeexpr(OP_FCOUNT, 1, yyvsp[-1], 0);;
    break;}
case 59:
#line 201 "HW4-sql.ypp"
{ yyval =  makeexpr(OP_FAVG, 1, yyvsp[-1], 0);;
    break;}
case 60:
#line 205 "HW4-sql.ypp"
{ yyval = yyvsp[0]; ;
    break;}
case 61:
#line 207 "HW4-sql.ypp"
{ yyval = makeexpr(OP_PRODUCT, 2, yyvsp[-2], yyvsp[0]); ;
    break;}
case 62:
#line 210 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 63:
#line 211 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 64:
#line 212 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, makeexpr(OP_NULL,0,0, 0), 0); ;
    break;}
case 65:
#line 213 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 66:
#line 214 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 67:
#line 215 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, makeexpr(OP_NULL, 0, 0, 0), yyvsp[-2]); ;
    break;}
case 68:
#line 222 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], 0); ;
    break;}
case 69:
#line 224 "HW4-sql.ypp"
{ yyval = makeexpr(OP_RLIST, 2, yyvsp[0], yyvsp[-2]); ;
    break;}
case 70:
#line 228 "HW4-sql.ypp"
{ yyval = makeexpr(OP_COLUMNDEF, 2, yyvsp[0], 0); ;
    break;}
case 71:
#line 230 "HW4-sql.ypp"
{ yyval = makeexpr(OP_COLUMNDEF, 2, yyvsp[-1], 1); ;
    break;}
case 72:
#line 232 "HW4-sql.ypp"
{ yyval = makeexpr(OP_COLUMNDEF, 2, yyvsp[-2], 3); ;
    break;}
case 73:
#line 235 "HW4-sql.ypp"
{ yyval = OP_EQUAL; ;
    break;}
case 74:
#line 236 "HW4-sql.ypp"
{ yyval = OP_NOTEQ; ;
    break;}
case 75:
#line 237 "HW4-sql.ypp"
{ yyval = OP_GT; ;
    break;}
case 76:
#line 238 "HW4-sql.ypp"
{ yyval = OP_LT; ;
    break;}
case 77:
#line 239 "HW4-sql.ypp"
{ yyval = OP_GEQ; ;
    break;}
case 78:
#line 240 "HW4-sql.ypp"
{ yyval = OP_LEQ; ;
    break;}
case 79:
#line 241 "HW4-sql.ypp"
{ yyval = OP_PLUS; ;
    break;}
case 80:
#line 242 "HW4-sql.ypp"
{ yyval = OP_BMINUS; ;
    break;}
case 81:
#line 243 "HW4-sql.ypp"
{ yyval = OP_TIMES; ;
    break;}
case 82:
#line 244 "HW4-sql.ypp"
{ yyval = OP_DIVIDE; ;
    break;}
case 83:
#line 245 "HW4-sql.ypp"
{ yyval = OP_AND; ;
    break;}
case 84:
#line 246 "HW4-sql.ypp"
{ yyval = OP_OR; ;
    break;}
case 85:
#line 247 "HW4-sql.ypp"
{ yyval = OP_IN; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 250 "HW4-sql.ypp"

int
yyerror(char const *str)
{
	printf("Line %d: %s\n", linenum, str);
	return 1;
}

